### ISSUE TITLE
dependency issues when running the js file and the exe file

### ISSUE THREAD

**Issue by RoguedBear** [jojo2357/Music-Discord-Rich-Presence-Library#13]
### Error log when running the `exe`:
```
PS D:\Portable Program Files\Music-Discord-Rich-Presence-Library> ./musicdl.exe
pkg/prelude/bootstrap.js:1244
      throw error;
      ^

Error: Cannot find module '../build/Release/canvas.node'
Require stack:
- C:\snapshot\itunes-artwork-finder\node_modules\resemblejs\node_modules\canvas\lib\bindings.js
- C:\snapshot\itunes-artwork-finder\node_modules\resemblejs\node_modules\canvas\lib\canvas.js
- C:\snapshot\itunes-artwork-finder\node_modules\resemblejs\node_modules\canvas\index.js
- C:\snapshot\itunes-artwork-finder\node_modules\resemblejs\resemble.js
- C:\snapshot\itunes-artwork-finder\node_modules\resemblejs\compareImages.js
- C:\snapshot\itunes-artwork-finder\musicdl.js
1) If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it from filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.execPath.
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:964:15)
    at Function.Module._resolveFilename (pkg/prelude/bootstrap.js:1346:46)
    at Function.Module._load (internal/modules/cjs/loader.js:840:27)
    at Module.require (internal/modules/cjs/loader.js:1024:19)
    at Module.require (pkg/prelude/bootstrap.js:1225:31)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\snapshot\itunes-artwork-finder\node_modules\resemblejs\node_modules\canvas\lib\bindings.js:3:18)
    at Module._compile (pkg/prelude/bootstrap.js:1320:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1156:10)
    at Module.load (internal/modules/cjs/loader.js:984:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\snapshot\\itunes-artwork-finder\\node_modules\\resemblejs\\node_modules\\canvas\\lib\\bindings.js',
    'C:\\snapshot\\itunes-artwork-finder\\node_modules\\resemblejs\\node_modules\\canvas\\lib\\canvas.js',
    'C:\\snapshot\\itunes-artwork-finder\\node_modules\\resemblejs\\node_modules\\canvas\\index.js',
    'C:\\snapshot\\itunes-artwork-finder\\node_modules\\resemblejs\\resemble.js',
    'C:\\snapshot\\itunes-artwork-finder\\node_modules\\resemblejs\\compareImages.js',
    'C:\\snapshot\\itunes-artwork-finder\\musicdl.js'
  ],
  pkg: true
}
```

### Error log when running from node:
```
PS D:\Portable Program Files\Music-Discord-Rich-Presence-Library> node musicdl.js
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'resemblejs/compareImages'
Require stack:
- D:\Portable Program Files\Music-Discord-Rich-Presence-Library\musicdl.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (D:\Portable Program Files\Music-Discord-Rich-Presence-Library\musicdl.js:10:18)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'D:\\Portable Program Files\\Music-Discord-Rich-Presence-Library\\musicdl.js'
  ]
}
```

**Comment by jojo2357** [comment]
Oopsies i added more deps (this time to detect duplicate album arts) and i guess they need to be included as well. Ez fix but im kinda busy so forgive me for not being fast to close this (also i know you have npm)

Plus i found bugs in the c# that this recent update caused so gotta fix those too

**Comment by RoguedBear** [comment]
oh it's fine. you can take your time. I'll deploy my ⚡ quick-fixes ⚡ locally meanwhile

**Comment by Smaltin** [comment]
Yeah, it just needs a quick `npm i resemblejs`

**Comment by jojo2357** [comment]
Pls verify recent commit

**Comment by RoguedBear** [comment]
Yes the exe is working!
