### ISSUE TITLE
musicdl.exe crashes if node_modules folder is not present

### ISSUE THREAD

**Issue by RoguedBear** [jojo2357/Music-Discord-Rich-Presence-Library#6]
Double clicking the exe would open-close the command line window and running through command line gives the below mentioned error. So I tried running the script by node, which ended up in me installing jsmediatags (as usual), and sharp module.

When the module folder `node_modules/` is present the exe runs fine

error log running the exe through command line:
```
PS D:\Portable Program Files\Music-Discord-Rich-Presence-Library - Copy> ./musicdl.exe
Require stack:
- C:\snapshot\itunes-artwork-finder\node_modules\sharp\lib\constructor.js
- C:\snapshot\itunes-artwork-finder\node_modules\sharp\lib\index.js
- C:\snapshot\itunes-artwork-finder\musicdl.js
1) If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it from filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.execPath.

- Run "npm rebuild --verbose sharp" and look for errors
- Consult the installation documentation at https://sharp.pixelplumbing.com/install
- Search for this error at https://github.com/lovell/sharp/issues

    at Object.<anonymous> (C:\snapshot\itunes-artwork-finder\node_modules\sharp\lib\constructor.js:34:9)
    at Module._compile (pkg/prelude/bootstrap.js:1320:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1156:10)
    at Module.load (internal/modules/cjs/loader.js:984:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Module.require (internal/modules/cjs/loader.js:1024:19)
    at Module.require (pkg/prelude/bootstrap.js:1225:31)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\snapshot\itunes-artwork-finder\node_modules\sharp\lib\index.js:3:15)
    at Module._compile (pkg/prelude/bootstrap.js:1320:22)
```

music.dl when `node_modules/` is present:
```
PS D:\Portable Program Files\Music-Discord-Rich-Presence-Library> ./musicdl.exe
Who is this (github username is good, just for naming your files for the library)
```

**Comment by jojo2357** [comment]
Grrrr i saw something come up at compile time so i didnt think much of it but ill look into it, thanks. (Not grrring you btw just that there is an issue)
